### ISSUE TITLE
Stuck on init in ubuntu server

### ISSUE THREAD

**Issue by FSchiltz** [Chibald/maestrogateway#32]
Hello,

I updated the container and now maestrogateway seems stuck in the config and does not start connecting to the stove.
My server is on ubuntu server 21.04 up to date.
My docker-compose:
```
maestrogateway:
    container_name: maestrogateway
    image: chibald/maestrogateway:v1.02
    networks:
      - proxy
    environment:      
      MQTT_ip: 'mqttbroker'
      MQTT_port: 1883
      MQTT_authentication: 'True'
      MQTT_user: 'mqtt'
      MQTT_pass: 'mqtt'
      MQTT_TOPIC_SUB: 'SUBmcz'
      MQTT_TOPIC_PUB: 'PUBmcz'
      MQTT_PAYLOAD_TYPE: 'TOPIC'
      WS_RECONNECTS_BEFORE_ALERT: 1
      MCZip: '192.168.120.1'
      MCZport: '81'
    restart: always

networks:
  proxy: # this is the external network
    name: proxy
  mqtt: #network t`
```

The docker compose up log:
```
Attaching to maestrogateway
maestrogateway  | Starting Maestrogateway.
maestrogateway  | Systemd is not available. This is the case on docker alpine images and on windows machines
maestrogateway  | 2021-10-13 12:28:18,111 :: __main__ :: INFO :: Starting Maestro Daemon
maestrogateway  | Reading config from envionment variables
maestrogateway  | 2021-10-13 12:28:18,111 :: __main__ :: INFO :: Connection in progress to the MQTT broker (IP:mqttbroker PORT:1883)
maestrogateway  | mqtt authentication enabled
maestrogateway  | 2021-10-13 12:28:18,113 :: __main__ :: INFO :: MQTT: Subscribed to topic "SUBmcz#"
maestrogateway  | 2021-10-13 12:28:18,113 :: __main__ :: INFO :: MQTT: Connected to broker. 0

```

How can I get more log ?
