### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by lyazide** [Chibald/maestrogateway#48]
When running the docker with docker compose I get the following error : 
```
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1  | exec /usr/local/bin/python3: exec format error
mcz-maestrogateway-1 exited with code 1
```
Here is the compose file:

```
version: '3.3'
services:

  maestrogateway:
    image: chibald/maestrogateway:latest
    network_mode: host
    environment:      
      MQTT_ip: '192.168.xxx.xxx'
      MQTT_port: 1883
      MQTT_authentication: 'False'
      MQTT_user: ''
      MQTT_pass: ''
      MQTT_TOPIC_SUB: 'Maestro/Command/'
      MQTT_TOPIC_PUB: 'Maestro/'
      MQTT_PAYLOAD_TYPE: 'TOPIC'
      WS_RECONNECTS_BEFORE_ALERT: 5
      MCZip: '192.168.120.1'
      MCZport: '81'

    restart: unless-stopped
```
